root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "build", "frontend"]
  delay = 1000

[color]
  main = "magenta"
  watcher = "cyan" 
  build = "yellow"
  runner = "green"